# Site settings
title: Belajar O365
email: 
description: > # this means to ignore newlines until "baseurl:"
  Belajar dan Mengenal Office 365.
baseurl: "/belajar-O365" # the subpath of your site, e.g. /blog/
url: "http://cah.unpkediri.ac.id" # the base hostname & protocol for your site
twitter_username: saifulindo
github_username: saifulindo

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
